// Generated by scripts/generate-mdx-data.mjs
export const mdxData = {
  "courses": {
    "introduction-to-anchor": {
      "metadata": {
        "title": "Introduction to Anchor",
        "language": "Anchor",
        "color": "221,234,224",
        "difficulty": 1,
        "isFeatured": true,
        "status": "Unclaimed",
        "totalLessons": 2
      },
      "lessons": [
        {
          "title": "Getting Started with Anchor",
          "lessonNumber": 1
        },
        {
          "title": "Getting Cracked at Anchor",
          "lessonNumber": 2
        }
      ]
    },
    "quantum-vault": {
      "metadata": {
        "title": "Quantum Vault",
        "language": "Rust",
        "color": "255,173,102",
        "difficulty": 4,
        "isFeatured": true,
        "status": "Claimed",
        "totalLessons": 1
      },
      "lessons": [
        {
          "title": "Introduction to Quantum Vault",
          "lessonNumber": 1
        }
      ]
    },
    "your-first-spl-token": {
      "metadata": {
        "title": "Your First SPL Token",
        "language": "Typescript",
        "color": "105,162,241",
        "difficulty": 2,
        "isFeatured": true,
        "status": "Locked",
        "totalLessons": 1
      },
      "lessons": [
        {
          "title": "Understanding SPL Tokens",
          "lessonNumber": 1
        }
      ]
    }
  },
  "lessons": {
    "introduction-to-anchor": {
      "getting-cracked-at-anchor": {
        "metadata": {
          "title": "Getting Cracked at Anchor",
          "lessonNumber": 2
        }
      },
      "getting-started-with-anchor": {
        "metadata": {
          "title": "Getting Started with Anchor",
          "lessonNumber": 1
        }
      }
    },
    "quantum-vault": {
      "introduction-to-quantum-vault": {
        "metadata": {
          "title": "Introduction to Quantum Vault",
          "lessonNumber": 1
        }
      }
    },
    "your-first-spl-token": {
      "understanding-spl-tokens": {
        "metadata": {
          "title": "Understanding SPL Tokens",
          "lessonNumber": 1
        }
      }
    }
  }
};